/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRecentAlertsRouteImport } from './routes/_app.recent-alerts'
import { Route as AppHighRiskRouteImport } from './routes/_app.high-risk'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppConversationsConversationIdRouteImport } from './routes/_app.conversations.$conversationId'
import { Route as AppChildChildIdRouteImport } from './routes/_app.child.$childId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecentAlertsRoute = AppRecentAlertsRouteImport.update({
  id: '/recent-alerts',
  path: '/recent-alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppHighRiskRoute = AppHighRiskRouteImport.update({
  id: '/high-risk',
  path: '/high-risk',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsConversationIdRoute =
  AppConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AppConversationsRoute,
  } as any)
const AppChildChildIdRoute = AppChildChildIdRouteImport.update({
  id: '/child/$childId',
  path: '/child/$childId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/conversations': typeof AppConversationsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/high-risk': typeof AppHighRiskRoute
  '/recent-alerts': typeof AppRecentAlertsRoute
  '/child/$childId': typeof AppChildChildIdRoute
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/conversations': typeof AppConversationsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/high-risk': typeof AppHighRiskRoute
  '/recent-alerts': typeof AppRecentAlertsRoute
  '/child/$childId': typeof AppChildChildIdRoute
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/conversations': typeof AppConversationsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/high-risk': typeof AppHighRiskRoute
  '/_app/recent-alerts': typeof AppRecentAlertsRoute
  '/_app/child/$childId': typeof AppChildChildIdRoute
  '/_app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/conversations'
    | '/dashboard'
    | '/high-risk'
    | '/recent-alerts'
    | '/child/$childId'
    | '/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/conversations'
    | '/dashboard'
    | '/high-risk'
    | '/recent-alerts'
    | '/child/$childId'
    | '/conversations/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alerts'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/high-risk'
    | '/_app/recent-alerts'
    | '/_app/child/$childId'
    | '/_app/conversations/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/recent-alerts': {
      id: '/_app/recent-alerts'
      path: '/recent-alerts'
      fullPath: '/recent-alerts'
      preLoaderRoute: typeof AppRecentAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/high-risk': {
      id: '/_app/high-risk'
      path: '/high-risk'
      fullPath: '/high-risk'
      preLoaderRoute: typeof AppHighRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations/$conversationId': {
      id: '/_app/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AppConversationsConversationIdRouteImport
      parentRoute: typeof AppConversationsRoute
    }
    '/_app/child/$childId': {
      id: '/_app/child/$childId'
      path: '/child/$childId'
      fullPath: '/child/$childId'
      preLoaderRoute: typeof AppChildChildIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppConversationsRouteChildren {
  AppConversationsConversationIdRoute: typeof AppConversationsConversationIdRoute
}

const AppConversationsRouteChildren: AppConversationsRouteChildren = {
  AppConversationsConversationIdRoute: AppConversationsConversationIdRoute,
}

const AppConversationsRouteWithChildren =
  AppConversationsRoute._addFileChildren(AppConversationsRouteChildren)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppConversationsRoute: typeof AppConversationsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHighRiskRoute: typeof AppHighRiskRoute
  AppRecentAlertsRoute: typeof AppRecentAlertsRoute
  AppChildChildIdRoute: typeof AppChildChildIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppConversationsRoute: AppConversationsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHighRiskRoute: AppHighRiskRoute,
  AppRecentAlertsRoute: AppRecentAlertsRoute,
  AppChildChildIdRoute: AppChildChildIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
